name: Deploy to Minikube using GitHub Actions

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    name: Build Node.js Docker Image and Deploy to Minikube
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start Minikube
        uses: medyagh/setup-minikube@master
        with:
          driver: docker

      - name: Verify Minikube Cluster
        run: kubectl get pods -A

      - name: Build Docker image inside Minikube
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker build -t devopshint/node-app:latest .
          docker images

      - name: Deploy Node.js app to Minikube
        run: |
          kubectl apply -f k8s-node-app.yaml
          kubectl get all

      - name: Wait for Pod to be Ready
        run: |
          kubectl wait --for=condition=ready pod -l app=nodejs-app --timeout=60s

      - name: Get service URL
        run: |
          minikube service list
          minikube service nodejs-app --url
